### ISSUE TITLE
minor typo: it return twice should be hit return twice

### ISSUE THREAD

**Issue by umbrellaid** [james-stoup/org-mode-better-defaults#1]
https://github.com/james-stoup/org-mode-better-defaults/blob/25f827e546883653940cc4309409424f3510385e/README.org?plain=1#L245

minor typo "it return twice" should be "hit return twice"

Thank you for putting together this amazing set of org resources.

**Comment by james-stoup** [comment]
Good catch. I fixed it. Thanks for reading and please let me know if you find any more typos.

**Comment by james-stoup** [comment]
Fixed.
